export enum authTypes {
    CREATE_USER_REQUEST = "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE = "CREATE_USER_FAILURE",
    SHOW_ALERT_MESSAGE="SHOW_ALERT_MESSAGE"
  }
  