export enum loginTypes {
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    SHOW_ALERT_MESSAGE="SHOW_ALERT_MESSAGE",
    LOGOUT = 'LOGOUT'
  }
  